site_name: ekpmeasure
nav: 
  - Home: index.md
  - Getting Started: start.md
  - Code Reference:
    - analysis.core: analysis-core-reference.md
    - analysis.load: analysis-load-reference.md
    - analysis.FE_switching: analysis-fe_switching-reference.md

theme: readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings